import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const primaryFont = localFont({
  src: './fonts/Oakes-Grotesk-Regular.ttf',
  variable: '--font-custom',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${primaryFont.variable}
        `}>
          {children}
      </body>
    </html>
  );
}
